---
smtp:
    server: "smtp.example.com:587"
    rrom: "alert@example.com"
    to: "admin@example.com"
    logSelect: "auth"
watch:
    waitInMilliSecs: "3000"
rootFs:
    folder: "root/"
    scanFolder: "root/scan/"
    outFolder: "root/out/"
    sdFolder: "root/out/480"
    hdFolder: "root/out/720"
    fhdFolder: "root/out/1080"
